// SPDX-License-Identifier: MIT
//
// @metaharness/kernel runtime resolver. Per ADR-002a, the kernel ships as Rust
// source compiled to wasm + per-platform NAPI-RS for speed. BUT neither of
// those is guaranteed to be present in a plain `npm install` (the wasm pkg/
// is built by a separate CI job; the NAPI platform packages are optional).
// Without a fallback, `loadKernel()` threw ERR_MODULE_NOT_FOUND and every
// generated harness was dead on arrival. This module therefore ALWAYS has a
// third backend: a dependency-free pure-JS implementation. native > wasm > js,
// but js is the floor — the kernel is always loadable. (ADR-002a §fallback.)

import { createRequire } from 'node:module';

export type { McpServerSpec, ToolSpec, AgentSpec, HookSpec, HarnessSpec, HostAdapter } from './types.js';

export interface KernelInfo {
  version: string;
  git_sha: string;
  target: string;
}

interface KernelBackend {
  kernelInfo(): KernelInfo;
  mcpValidate(specJson: string): string | null;
  version(): string;
  backend: 'native' | 'wasm' | 'js';
}

let _cached: KernelBackend | null = null;

// GH #20/#22: remember WHY a higher-tier backend was unavailable so `doctor`
// and a requested-but-missing backend can report the actual reason instead of
// silently using js.
const _backendErrors: { native?: string; wasm?: string } = {};

async function loadNative(): Promise<KernelBackend | null> {
  const plat = `${process.platform}-${process.arch}`;
  const map: Record<string, string> = {
    'darwin-arm64': '@metaharness/kernel-darwin-arm64',
    'darwin-x64': '@metaharness/kernel-darwin-x64',
    'linux-x64': '@metaharness/kernel-linux-x64-gnu',
    'linux-arm64': '@metaharness/kernel-linux-arm64-gnu',
    'win32-x64': '@metaharness/kernel-win32-x64-msvc',
  };
  const pkg = map[plat];
  if (!pkg) {
    _backendErrors.native = `no native package mapping for platform "${plat}"`;
    return null;
  }
  try {
    const mod: any = await import(pkg);
    return {
      kernelInfo: () => mod.kernelInfo(),
      mcpValidate: (s: string) => mod.mcpValidate(s) ?? null,
      version: () => mod.version(),
      backend: 'native',
    };
  } catch (e) {
    _backendErrors.native = `optional dependency "${pkg}" not installed (${(e as Error).message})`;
    return null;
  }
}

async function loadWasm(): Promise<KernelBackend | null> {
  try {
    // @ts-ignore — generated by `wasm-pack build --target nodejs` into ../pkg/.
    // The nodejs target is CommonJS and auto-initializes the wasm on require
    // (no init() call). pkg/package.json carries {"type":"commonjs"} (GH #21)
    // so this ESM module loads the CJS shim correctly; ESM interop puts the
    // exports on `.default` (and, via cjs-module-lexer, as named exports too).
    const mod: any = await import('../pkg/ruflo_kernel_wasm.js');
    const api: any = typeof mod.kernelInfo === 'function' ? mod : (mod.default ?? mod);
    if (typeof api.kernelInfo !== 'function') {
      throw new Error('wasm shim loaded but kernelInfo() is missing');
    }
    return {
      kernelInfo: () => api.kernelInfo(),
      mcpValidate: (s: string) => api.mcpValidate(s) ?? null,
      version: () => api.version(),
      backend: 'wasm',
    };
  } catch (e) {
    _backendErrors.wasm = `wasm artifact (pkg/ruflo_kernel_wasm.js) not present in @metaharness/kernel (${(e as Error).message})`;
    return null;
  }
}

/**
 * The kernel's own version, read from its package.json. Cached. Falls back to
 * '0.0.0' only if the package.json is somehow unreadable (never expected).
 */
let _version: string | null = null;
function kernelVersion(): string {
  if (_version) return _version;
  try {
    const require = createRequire(import.meta.url);
    // dist/index.js → ../package.json
    _version = (require('../package.json') as { version?: string }).version ?? '0.0.0';
  } catch {
    _version = '0.0.0';
  }
  return _version;
}

/**
 * Pure-JS kernel backend — zero native/wasm dependencies, always available.
 * It reimplements the load-bearing kernel surface (kernelInfo / version /
 * mcpValidate) in TypeScript so a harness installed from npm works with no
 * compiled artifacts. The validation rules mirror crates/kernel/src/mcp.rs
 * exactly (server name non-empty; command XOR url) so behaviour is identical
 * whether the native, wasm, or js backend answers.
 */
function loadJs(): KernelBackend {
  return {
    kernelInfo: () => ({
      version: kernelVersion(),
      git_sha: 'js',
      target: `${process.platform}-${process.arch}`,
    }),
    version: () => kernelVersion(),
    mcpValidate: (specJson: string): string | null => {
      let spec: { name?: unknown; command?: unknown; url?: unknown };
      try {
        spec = JSON.parse(specJson);
      } catch (e) {
        // Mirror the NAPI binding, which throws on unparseable spec JSON.
        throw new Error(`invalid spec json: ${(e as Error).message}`);
      }
      // Rules, byte-for-byte from crates/kernel/src/mcp.rs::validate. The real
      // kernel surfaces these through `Error::Mcp(..)`, whose Display prefixes
      // "mcp: " — so native + wasm return "mcp: <reason>". The js floor must
      // match exactly (GH #20: drift surfaced once wasm became loadable).
      if (typeof spec.name !== 'string' || spec.name.length === 0) {
        return 'mcp: server name is empty';
      }
      const hasCommand = Array.isArray(spec.command) && spec.command.length > 0;
      const hasUrl = typeof spec.url === 'string' && spec.url.length > 0;
      if (hasCommand && hasUrl) return 'mcp: command and url are mutually exclusive';
      if (!hasCommand && !hasUrl) return 'mcp: either command or url must be set';
      return null;
    },
    backend: 'js',
  };
}

/**
 * Load the kernel. native > wasm > pure-JS. The JS backend is the floor, so
 * this never rejects with a missing-module error. Cached.
 */
/** Test-only: clear the cached backend + recorded errors so a subsequent
 * loadKernel() re-resolves (e.g. after changing METAHARNESS_KERNEL_BACKEND). */
export function _resetKernelCacheForTests(): void {
  _cached = null;
  delete _backendErrors.native;
  delete _backendErrors.wasm;
}

export async function loadKernel(): Promise<KernelBackend> {
  if (_cached) return _cached;
  // GH #22: honor METAHARNESS_KERNEL_BACKEND=native|wasm|js. When a specific
  // backend is requested but cannot load, FAIL LOUDLY with the reason instead
  // of silently using js.
  const requested = (process.env.METAHARNESS_KERNEL_BACKEND || '').trim().toLowerCase();
  if (requested && !['native', 'wasm', 'js'].includes(requested)) {
    throw new Error(
      `METAHARNESS_KERNEL_BACKEND="${requested}" is invalid; choose one of: native, wasm, js`,
    );
  }
  if (requested === 'js') {
    _cached = loadJs();
    return _cached;
  }
  if (requested === 'native') {
    const n = await loadNative();
    if (!n) {
      throw new Error(
        `kernel backend "native" was requested but is unavailable: ${_backendErrors.native ?? 'unknown reason'}. ` +
          `Unset METAHARNESS_KERNEL_BACKEND to fall back to js.`,
      );
    }
    _cached = n;
    return _cached;
  }
  if (requested === 'wasm') {
    const w = await loadWasm();
    if (!w) {
      throw new Error(
        `kernel backend "wasm" was requested but is unavailable: ${_backendErrors.wasm ?? 'unknown reason'}. ` +
          `Unset METAHARNESS_KERNEL_BACKEND to fall back to js.`,
      );
    }
    _cached = w;
    return _cached;
  }
  // Auto: native > wasm > pure-JS (the floor).
  _cached = (await loadNative()) ?? (await loadWasm()) ?? loadJs();
  return _cached;
}

/**
 * GH #20/#22: backend diagnostics for `doctor` and honest capability reporting.
 * Returns the resolved backend, the requested backend (if any), and the reason
 * each higher-tier backend was unavailable. Triggers resolution if needed.
 */
export interface KernelDiagnostics {
  resolved: 'native' | 'wasm' | 'js';
  requested: string | null;
  reasons: { native?: string; wasm?: string };
}

export async function kernelDiagnostics(): Promise<KernelDiagnostics> {
  const k = await loadKernel();
  const requested = (process.env.METAHARNESS_KERNEL_BACKEND || '').trim().toLowerCase() || null;
  return { resolved: k.backend, requested, reasons: { ..._backendErrors } };
}
